"use client";

import Link from "next/link";
import Image from "next/image";
import { ChangeEvent, useMemo, useRef, useState } from "react";
import { AppShell } from "../components/AppShell";
import { serverSnapshot, setLocalStorageValue, useLocalStorageValue } from "../lib/localStorage";

type Settings = {
  workspaceName: string; language: string; timezone: string; userName: string; userEmail: string; userRole: string; institution: string; avatar: string; accentColor: string; webhookUrl: string; apiKey: string; timeout: string; model: string; questionStyle: string; includeExplanations: boolean; citeSource: boolean; defaultQuestions: string; defaultDifficulty: string; defaultFormat: string; defaultSubject: string; defaultInstructions: string; notifyReady: boolean; notifyWeekly: boolean; notifyErrors: boolean; notifyProduct: boolean; theme: string; reduceMotion: boolean; density: string;
};

const defaults: Settings = { workspaceName: "QuizAI Studio", language: "en", timezone: "auto", userName: "", userEmail: "", userRole: "teacher", institution: "", avatar: "", accentColor: "#d0623a", webhookUrl: "", apiKey: "", timeout: "60", model: "auto", questionStyle: "academic", includeExplanations: true, citeSource: false, defaultQuestions: "20", defaultDifficulty: "medium", defaultFormat: "multiple_choice", defaultSubject: "", defaultInstructions: "", notifyReady: true, notifyWeekly: false, notifyErrors: true, notifyProduct: false, theme: "light", reduceMotion: false, density: "comfortable" };
const sections = ["general", "profile", "ai", "defaults", "notifications", "appearance", "usage", "danger"] as const;
const sectionLabels = { general: "General", profile: "Profile", ai: "AI Engine", defaults: "Quiz Defaults", notifications: "Notifications", appearance: "Appearance", usage: "Usage", danger: "Advanced" };

function Field({ label, hint, children }: { label: string; hint: string; children: React.ReactNode }) { return <div className="grid gap-3 border-b border-line py-4 last:border-0 last:pb-0 sm:grid-cols-[190px_1fr]"><div><strong className="block text-xs font-medium">{label}</strong><span className="mt-1 block text-[11px] leading-relaxed text-muted">{hint}</span></div><div>{children}</div></div>; }
function Icon({ children }: { children: React.ReactNode }) { return <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>; }
function Input({ value, onChange, type = "text", placeholder = "" }: { value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-line bg-cream-soft px-3 py-2 text-xs outline-none transition-colors focus:border-rust" />; }
function Select({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: [string, string][] }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-md border border-line bg-cream-soft px-3 py-2 text-xs outline-none focus:border-rust">{options.map(([option, label]) => <option key={option} value={option}>{label}</option>)}</select>; }

export default function SettingsPage() {
  const settingsValue = useLocalStorageValue("quizai_settings");

  if (settingsValue === serverSnapshot) return null;

  let initial = defaults;
  try { initial = { ...defaults, ...JSON.parse(settingsValue || "{}") }; } catch { /* Use defaults when storage is invalid. */ }
  return <SettingsEditor initial={initial} />;
}

function SettingsEditor({ initial }: { initial: Settings }) {
  const [section, setSection] = useState<(typeof sections)[number]>("general");
  const [saved, setSaved] = useState<Settings>(initial);
  const [pending, setPending] = useState<Settings>(initial);
  const [toast, setToast] = useState("");
  const avatarInput = useRef<HTMLInputElement>(null);
  const importInput = useRef<HTMLInputElement>(null);
  const changed = useMemo(() => JSON.stringify(saved) !== JSON.stringify(pending), [saved, pending]);

  function update<Key extends keyof Settings>(key: Key, value: Settings[Key]) { setPending((current) => ({ ...current, [key]: value })); }
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 3000); }
  function save() { setLocalStorageValue("quizai_settings", JSON.stringify(pending)); setSaved(pending); notify("Settings saved successfully"); }
  function discard() { setPending(saved); notify("Changes discarded"); }
  function reset() { if (window.confirm("Reset all settings to their default values?")) { setSaved(defaults); setPending(defaults); setLocalStorageValue("quizai_settings", JSON.stringify(defaults)); notify("Settings reset to defaults"); } }
  function clearAll() { if (window.confirm("This will delete all workspace data. Continue?")) { localStorage.clear(); setSaved(defaults); setPending(defaults); notify("All workspace data cleared"); } }
  function exportSettings() { const url = URL.createObjectURL(new Blob([JSON.stringify(saved, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `quizai-settings-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); notify("Settings exported"); }
  function importSettings(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { setPending({ ...defaults, ...JSON.parse(String(reader.result)) }); notify("Settings imported — review and save"); } catch { notify("Invalid settings file"); } }; reader.readAsText(file); event.target.value = ""; }
  async function testWebhook() { if (!pending.webhookUrl) return notify("No URL provided"); try { const url = new URL(pending.webhookUrl); if (!["http:", "https:"].includes(url.protocol)) throw new Error(); await fetch(url, { method: "POST", mode: "no-cors", body: new FormData() }); notify("Webhook URL reachable"); } catch { notify("Webhook connection failed"); } }
  function uploadAvatar(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => update("avatar", String(reader.result)); reader.readAsDataURL(file); event.target.value = ""; }

  const history = typeof window === "undefined" ? [] : (() => { try { return JSON.parse(localStorage.getItem("quizai_history") || "[]"); } catch { return []; } })();
  const monthHistory = history.filter((item: { createdAt: number }) => { const date = new Date(item.createdAt); const now = new Date(); return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear(); });
  const usage = { assessments: monthHistory.length, documents: monthHistory.reduce((sum: number, item: { fileCount?: number }) => sum + Number(item.fileCount || 1), 0), questions: monthHistory.reduce((sum: number, item: { questions?: number }) => sum + Number(item.questions || 0), 0) };

  return <AppShell active="settings"><div className="mx-auto max-w-6xl px-4 sm:px-6">
    <main className="grid gap-8 py-10 pb-28 lg:grid-cols-[220px_minmax(0,1fr)] lg:py-12"><aside className="lg:sticky lg:top-6 lg:h-fit"><h1 className="font-sans text-2xl font-semibold tracking-tight">Settings</h1><p className="mt-2 text-xs leading-relaxed text-muted">Manage your workspace and preferences.</p><nav className="mt-6 flex gap-1 overflow-x-auto lg:flex-col">{sections.map((name) => <button type="button" key={name} onClick={() => setSection(name)} className={`whitespace-nowrap rounded-md px-3 py-2 text-left text-xs transition-colors ${section === name ? "bg-cream-soft font-medium text-ink" : "text-muted hover:bg-cream-soft hover:text-ink"}`}>{sectionLabels[name]}</button>)}</nav></aside>
    <div className="min-w-0"><div className="mb-8"><h2 className="font-sans text-2xl font-semibold tracking-tight">{sectionLabels[section]}</h2><p className="mt-2 text-sm text-ink-soft">{section === "general" ? "Configure your workspace name and basic preferences." : section === "profile" ? "Manage your personal information and how you appear." : section === "ai" ? "Configure the AI workflow that generates your assessments." : section === "defaults" ? "Set the default values used when creating new assessments." : section === "notifications" ? "Choose what updates you want to receive." : section === "appearance" ? "Customize how QuizAI Studio looks to you." : section === "usage" ? "Review your current workspace activity." : "Manage your data and workspace configuration."}</p></div>
      {section === "general" && <Panel title="Workspace" desc="The name displayed throughout the application."><Field label="Workspace name" hint="Displayed in the header and browser title."><Input value={pending.workspaceName} onChange={(value) => update("workspaceName", value)} /></Field><Field label="Language" hint="Interface language for the platform."><Select value={pending.language} onChange={(value) => update("language", value)} options={[["en", "English"], ["ar", "العربية"], ["es", "Español"], ["fr", "Français"], ["de", "Deutsch"]]} /></Field><Field label="Timezone" hint="Used for displaying dates and timestamps."><Select value={pending.timezone} onChange={(value) => update("timezone", value)} options={[["auto", "Automatic (browser)"], ["utc", "UTC"], ["est", "Eastern Time"], ["pst", "Pacific Time"], ["gmt", "GMT"], ["cet", "Central European"]]} /></Field></Panel>}
      {section === "profile" && <Panel title="Personal information" desc="Your identity within the QuizAI workspace."><Field label="Avatar" hint="A visual representation of you."><div className="flex items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-full bg-rust text-xl font-semibold text-cream">{pending.avatar ? <Image src={pending.avatar} alt="Avatar" width={56} height={56} unoptimized className="h-full w-full object-cover" /> : (pending.userName || pending.workspaceName || "Q")[0].toUpperCase()}</div><div className="flex gap-2"><input ref={avatarInput} type="file" accept="image/*" className="hidden" onChange={uploadAvatar} /><button type="button" onClick={() => avatarInput.current?.click()} className="rounded-md border border-line bg-cream-soft px-3 py-2 text-xs hover:border-ink/25">Upload image</button><button type="button" onClick={() => update("avatar", "")} className="rounded-md border border-line px-3 py-2 text-xs text-muted hover:text-rust">Remove</button></div></div></Field><Field label="Full name" hint="Your display name."><Input value={pending.userName} onChange={(value) => update("userName", value)} placeholder="e.g. John Smith" /></Field><Field label="Email" hint="Used for notifications and account recovery."><Input type="email" value={pending.userEmail} onChange={(value) => update("userEmail", value)} placeholder="you@example.com" /></Field><Field label="Role" hint="Your position within your institution."><Select value={pending.userRole} onChange={(value) => update("userRole", value)} options={[["teacher", "Teacher"], ["professor", "Professor"], ["ta", "Teaching Assistant"], ["admin", "Administrator"], ["student", "Student"], ["other", "Other"]]} /></Field><Field label="Institution" hint="Your school, university, or organization."><Input value={pending.institution} onChange={(value) => update("institution", value)} placeholder="e.g. Example University" /></Field></Panel>}
      {section === "ai" && <><Panel title="Webhook connection" desc="Connect to your n8n workflow for quiz generation."><Field label="Webhook URL" hint="The endpoint that receives documents and returns generated quizzes."><div className="flex gap-2"><Input type="url" value={pending.webhookUrl} onChange={(value) => update("webhookUrl", value)} placeholder="https://n8n.yourdomain.com/webhook/quiz-generator" /><button type="button" onClick={testWebhook} className="whitespace-nowrap rounded-md border border-line bg-cream-soft px-3 text-xs hover:border-rust">Test connection</button></div><span className="mt-1 block text-[10px] text-muted">Saved locally in this browser.</span></Field><Field label="API key" hint="Optional credential passed through your configured workflow."><Input type="password" value={pending.apiKey} onChange={(value) => update("apiKey", value)} placeholder="Your provider key" /></Field><Field label="Request timeout" hint="Maximum time to wait for the AI engine."><Select value={pending.timeout} onChange={(value) => update("timeout", value)} options={[["30", "30 seconds"], ["60", "1 minute"], ["120", "2 minutes"], ["300", "5 minutes"]]} /></Field></Panel><Panel title="AI behavior" desc="Fine-tune how the AI approaches question generation."><Field label="Model preference" hint="The AI model your workflow should prioritize."><Select value={pending.model} onChange={(value) => update("model", value)} options={[["auto", "Auto (recommended)"], ["fast", "Fast (lower quality)"], ["balanced", "Balanced"], ["premium", "Premium (slower, higher quality)"]]} /></Field><Field label="Question style" hint="Preferred approach to question construction."><Select value={pending.questionStyle} onChange={(value) => update("questionStyle", value)} options={[["academic", "Academic"], ["conversational", "Conversational"], ["technical", "Technical"]]} /></Field><ToggleField label="Answer explanations" hint="Add context to help learners understand the correct answer." checked={pending.includeExplanations} onChange={(value) => update("includeExplanations", value)} /><ToggleField label="Source citations" hint="Include page numbers or section references where possible." checked={pending.citeSource} onChange={(value) => update("citeSource", value)} /></Panel></>}
      {section === "defaults" && <Panel title="Default configuration" desc="These values will be pre-selected in the workspace."><Field label="Default question count" hint="Pre-selected when creating a new quiz."><Select value={pending.defaultQuestions} onChange={(value) => update("defaultQuestions", value)} options={[["10", "10 questions"], ["20", "20 questions"], ["30", "30 questions"], ["40", "40 questions"]]} /></Field><Field label="Default difficulty" hint="The starting difficulty level."><Select value={pending.defaultDifficulty} onChange={(value) => update("defaultDifficulty", value)} options={[["easy", "Easy"], ["medium", "Medium"], ["hard", "Hard"], ["mixed", "Mixed"]]} /></Field><Field label="Default format" hint="Preferred question type."><Select value={pending.defaultFormat} onChange={(value) => update("defaultFormat", value)} options={[["multiple_choice", "Multiple Choice"], ["true_false", "True / False"], ["short_answer", "Short Answer"], ["mixed", "Mixed"]]} /></Field><Field label="Default subject" hint="Automatically fills the subject field."><Input value={pending.defaultSubject} onChange={(value) => update("defaultSubject", value)} placeholder="e.g. Computer Science" /></Field><Field label="Custom AI instructions" hint="Added to every generation request."><textarea value={pending.defaultInstructions} onChange={(event) => update("defaultInstructions", event.target.value)} className="min-h-20 w-full resize-y rounded-md border border-line bg-cream-soft px-3 py-2 text-xs outline-none focus:border-rust" placeholder="e.g. Always include real-world examples" /></Field></Panel>}
      {section === "notifications" && <Panel title="Email notifications" desc="Get notified about important events via email."><ToggleField label="Generation complete" hint="Sent immediately after your quiz is ready." checked={pending.notifyReady} onChange={(value) => update("notifyReady", value)} /><ToggleField label="Activity digest" hint="Sent every Monday morning." checked={pending.notifyWeekly} onChange={(value) => update("notifyWeekly", value)} /><ToggleField label="Error alerts" hint="Notified when the AI engine encounters an issue." checked={pending.notifyErrors} onChange={(value) => update("notifyErrors", value)} /><ToggleField label="Newsletter" hint="Monthly updates on QuizAI Studio." checked={pending.notifyProduct} onChange={(value) => update("notifyProduct", value)} /></Panel>}
      {section === "appearance" && <Panel title="Theme" desc="Choose your preferred color scheme."><Field label="Color scheme" hint="The overall theme of the application."><div className="flex flex-wrap gap-2">{[["light", "Light"], ["dark", "Dark"], ["system", "System"]].map(([value, label]) => <button type="button" key={value} onClick={() => update("theme", value)} className={`rounded-md border px-4 py-2 text-xs ${pending.theme === value ? "border-rust bg-rust/10 text-rust" : "border-line bg-cream-soft text-muted"}`}>{label}</button>)}</div></Field><Field label="Accent color" hint="Used for interactive highlights."><div className="flex gap-3">{["#d0623a", "#14432a", "#b05c36", "#557a62"].map((color) => <button type="button" aria-label={`Use ${color} accent`} key={color} onClick={() => update("accentColor", color)} className={`h-8 w-8 rounded-full border-2 ${pending.accentColor === color ? "border-ink" : "border-transparent"}`} style={{ backgroundColor: color }} />)}</div></Field><ToggleField label="Reduce motion" hint="Minimize interface animations." checked={pending.reduceMotion} onChange={(value) => update("reduceMotion", value)} /><Field label="Density" hint="Choose how much content fits on screen."><Select value={pending.density} onChange={(value) => update("density", value)} options={[["comfortable", "Comfortable"], ["compact", "Compact"]]} /></Field></Panel>}
      {section === "usage" && <Panel title="Current month" desc="Your workspace activity for the current month."><div className="grid grid-cols-3 gap-3">{[[usage.assessments, "Assessments"], [usage.documents, "Documents"], [usage.questions, "Questions"]].map(([value, label]) => <div key={String(label)} className="rounded-lg border border-line bg-cream-soft p-4"><strong className="font-sans text-2xl">{value}</strong><span className="mt-1 block text-[10px] uppercase text-muted">{label}</span></div>)}</div><div className="mt-6"><div className="mb-2 flex justify-between text-xs"><span className="text-muted">Monthly assessment limit</span><span>{Math.min(100, usage.assessments)}%</span></div><div className="h-1.5 overflow-hidden rounded bg-ink/10"><div className="h-full rounded bg-rust" style={{ width: `${Math.min(100, usage.assessments)}%` }} /></div></div></Panel>}
      {section === "danger" && <><Panel title="Data management" desc="Export or reset your workspace data."><div className="flex flex-wrap gap-2"><button type="button" onClick={exportSettings} className="rounded-md border border-line bg-cream-soft px-3 py-2 text-xs hover:border-ink/25">Export as JSON</button><input ref={importInput} type="file" accept=".json" className="hidden" onChange={importSettings} /><button type="button" onClick={() => importInput.current?.click()} className="rounded-md border border-line bg-cream-soft px-3 py-2 text-xs hover:border-ink/25">Import JSON</button></div></Panel><Panel title="Danger zone" desc="Irreversible actions. Proceed with caution." danger><DangerAction label="Clear assessment history" hint="Remove all previously generated quizzes." action={() => { if (window.confirm("Clear all assessment history?")) { localStorage.removeItem("quizai_history"); notify("Assessment history cleared"); } }} /><DangerAction label="Reset all settings" hint="Restore all settings to their default values." action={reset} /><DangerAction label="Clear all workspace data" hint="Delete everything including history, settings, and preferences." action={clearAll} /></Panel></>}
      {changed && <div className="sticky bottom-5 mt-6 flex flex-col items-start justify-between gap-3 rounded-lg border border-line bg-cream-soft p-3 shadow-lg sm:flex-row sm:items-center"><span className="text-xs text-muted"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-rust" /> You have unsaved changes</span><div className="flex gap-2"><button type="button" onClick={discard} className="rounded-md border border-line px-3 py-2 text-xs text-muted">Discard</button><button type="button" onClick={save} className="rounded-md bg-forest px-3 py-2 text-xs font-semibold text-cream">Save changes</button></div></div>}
    </div></main>{toast && <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-md border border-forest/20 bg-forest px-4 py-2.5 text-xs text-cream shadow-lg">✓ {toast}</div>}</div></AppShell>;
}

function Panel({ title, desc, children, danger = false }: { title: string; desc: string; children: React.ReactNode; danger?: boolean }) { return <section className={`mb-4 overflow-hidden rounded-xl border bg-cream/70 ${danger ? "border-rust/25" : "border-line"}`}><div className="border-b border-line px-5 py-4 sm:px-6"><h3 className={`text-sm font-semibold ${danger ? "text-rust" : ""}`}>{title}</h3><p className="mt-1 text-xs text-muted">{desc}</p></div><div className="p-5 sm:px-6">{children}</div></section>; }
function ToggleField({ label, hint, checked, onChange }: { label: string; hint: string; checked: boolean; onChange: (value: boolean) => void }) { return <Field label={label} hint={hint}><label className="flex cursor-pointer items-center justify-between gap-4"><span className="text-xs text-muted">Enable this preference</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-rust" /></label></Field>; }
function DangerAction({ label, hint, action }: { label: string; hint: string; action: () => void }) { return <div className="flex flex-col justify-between gap-3 border-b border-line py-4 last:border-0 last:pb-0 sm:flex-row sm:items-center"><div><strong className="block text-xs font-medium">{label}</strong><span className="mt-1 block text-[11px] text-muted">{hint}</span></div><button type="button" onClick={action} className="self-start rounded-md border border-rust/30 px-3 py-2 text-xs text-rust hover:bg-rust/10">{label.includes("history") ? "Clear history" : label.includes("settings") ? "Reset settings" : "Clear everything"}</button></div>; }
